<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('APPS:admin.library.AdminBaseController');

/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
	
	public function run() {
		$service = $this->_loadConfigService();
		$config = $service->getValues('site');
		$this->setOutput($config, 'config');
	}
	
	public function dorunAction() {
		list($ifopen, $readifopen, $spaceifopen) = $this->getInput(array('ifopen', 'readifopen', 'spaceifopen'), 'post');

		$config = new PwConfigSet('site');
		$config->set('app.dongta.ifopen', intval($ifopen))
			->set('app.dongta.read.ifopen', intval($readifopen))
			->set('app.dongta.space.ifopen', intval($spaceifopen))
			->flush();

		$this->showMessage('operate.success');
	}

	private function _loadConfigService() {
		return Wekit::load('config.PwConfig');
	}
}

?>