<?php
defined('WEKIT_VERSION') or exit(403);
/**
 * 前台入口
 *
 * generated by phpwind.com
 */
class IndexController extends PwBaseController {
	
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		if (!Wekit::C('site', 'app.dongta.ifopen')) {
			$this->showError('动他一下应用，关闭了');
		}
		if (!$this->loginUser->isExists()) {
			$this->showError('login.not');
		}
	}
	
	/**
	 * 动他一下主页面
	 */
	public function run() {
		$act = include(Wind::getRealPath('EXT:dongta.conf.dongta.php', true));

		$perpage = 10;
		list($start, $limit) = Pw::page2limit($page, $perpage);
		$follows = $this->_getDs()->getFollows($this->loginUser->uid, $limit, $start);
		$userList = Wekit::load('user.PwUser')->fetchUserByUid(array_keys($follows));

		$this->setOutput($act, 'act');
		$this->setOutput($follows, 'follows');
		$this->setOutput($userList, 'userList');
	}
	
	/**
	 * 谁动了我页面
	 */
	public function myAction() {
		$page = intval($this->getInput('page', 'get'));
		$page < 1 && $page = 1;
		$perpage = 10;
		list($offset, $limit) = Pw::page2limit($page, $perpage);
		
		$act = include(Wind::getRealPath('EXT:dongta.conf.dongta.php', true));
		$total = Wekit::load('EXT:dongta.service.App_Dongta')->countByUid($this->loginUser->uid);
		$result = Wekit::load('EXT:dongta.service.App_Dongta')->getByUid($this->loginUser->uid, $limit, $offset);
		$uids = array();
		foreach ($result as $key => $value) {
			$value['content'] = str_replace('{Ta}', '你', $act[$value['act']][1]);
			$result[$key] = $value;
			$uids[] = $value['created_userid'];
		}
		$users = Wekit::load('user.PwUser')->fetchUserByUid($uids);

		$this->setOutput($result, 'result');
		$this->setOutput($users, 'users');
		$this->setOutput($page, 'page');
		$this->setOutput($perpage, 'perpage');
		$this->setOutput($total, 'count');
	}
	
	/**
	 * 发送动作页面，一般是ajax提交的数据
	 */
	public function sendAction() {
		$act = $this->getInput('act', 'post');
		$uid = $this->getInput('uid', 'post');
		if (!$act) {
			$this->showError('请选择动作');
		}
		if (!$uid) {
			$this->showError('请选择用户');
		}
		!is_array($uid) && $uid = array($uid);
		
		Wind::import('EXT:dongta.service.dm.App_Dongta_Dm');
		$service = Wekit::load('EXT:dongta.service.App_Dongta');
		$users = Wekit::load('user.PwUser')->fetchUserByUid($uid);
		$actMap = include(Wind::getRealPath('EXT:dongta.conf.dongta.php', true));

		$title = '<a href="' . WindUrlHelper::createUrl('space/index/run', array('uid' => $this->loginUser->uid)) . '">' . $this->loginUser->username . '</a> ' . str_replace('{Ta}', '你', $actMap[$act][1]);
		$content = $title . ' <br>[来自应用 <a href="' . WindUrlHelper::createUrl('app/dongta/index/run') . '">动他一下</a>]';

		foreach ($users as $key => $value) {
			$dm = new App_Dongta_Dm();
			$dm->setAct($act)
				->setTouid($value['uid'])
				->setCreatedUser($this->loginUser->uid, $this->loginUser->username)
				->setCreatedTime(Pw::getTime());
			$service->add($dm);

			Wekit::load('message.srv.PwNoticeService')->sendNotice($value['uid'], 'app', 0, array(
				'title' => $title,
				'content' => $content
			));
		}

		$this->showMessage('operate.success');
	}
	
	/**
	 * 数据动作列表，一般ajax获取数据用
	 */
	public function actAction() {
		$act = include(Wind::getRealPath('EXT:dongta.conf.dongta.php', true));
		$this->setOutput($act, 'act');
	}

	protected function _getDs() {
		return Wekit::load('attention.PwAttention');
	}
}

?>